### PR TITLE
basic infrastructure for malaria data subscription report

### PR DESCRIPTION
**Pull request by deeonwuli**
### :pushpin: References

-   **Issue:** Closes https://app.clickup.com/t/35y9uvn

### CODE REVIEW

**Review by xurxodev — CHANGES_REQUESTED** [review]
thanks @deeonwuli 

You have created a new report that can be run with the REACT_APP_REPORT_VARIANT=mal-subscription-status environment variable.

However, under that report in all folders data/mal-data-subscription, domain/mal-data-subscription, webapp/reports/mal-data-subscription the files are copied from the mal-data-approval report.

My advice is that initially you do not have all those files and start building your report paying attention to mal-data-approval.

If there is common code that can be shared it should be extracted to the common folders for both reports to use to avoid duplicate code. For example, you will see that in data/common/sql-views there are sql views shared by more than one report.

Surely there are many files that you will not need, so I think it is better to start simple and little by little and adding only what you need, avoiding falling into premature abstractions.

**Comment by deeonwuli** [comment]
> thanks @deeonwuli
> 
> This code has more sense. I don't know if you will need all files you have created because I don't know this report but now it's not a clone of other reports. It's possible that in the future you need to create abstractions in common folders also.
> 
> Only two minor comments:
> 
> * There is no script file to build the metadata for this report.
>   Under the script folder, every report has a script to create the necessary metadata as the report and other related metadata necessary to create in either server.
> * Every script should have an associated npm script or command. You can review for example  "build-mal-metadata" in package.json under scripts key.

i noticed that there's just one file for build-mal-metadata and build-nhwa-metadata each even though there are two nhwa reports. am i supposed to create a new script file to build metadata for this report or do i just make changes to the existing one?

**Review by xurxodev — CHANGES_REQUESTED** [review]
thanks @deeonwuli 

Now we have a separate script infrastructure to build metadata but it's a copy from build-mal-metadata. This script only should have the necessary code for this Report.

For example: to retrieve the datasets, we should filter by specific name fo this report but currently, it's filtering by  MAL - WMR Form like in build-mal-metadata.ts script.

Review the code in this script and only to maintain or modify the necessary

**Comment by MiquelAdell** [comment]
Discarding this PR as its functionality is provided by https://github.com/EyeSeeTea/d2-reports/pull/71

**Pull request closed without merging**
