### PR TITLE
Feat/audit filter reports infrastructure

### PR DESCRIPTION
**Pull request by deeonwuli**
### :pushpin: References

-   **Related Issue:**  https://app.clickup.com/t/860q2nvcz

### :art: Screenshots
Screenshot 2023-03-03 at 12 26 44

### CODE REVIEW

**Review by ifoche — CHANGES_REQUESTED** [review]
Thanks @deeonwuli . 

- The report lacks from a minor thing. You cannot select countries in the OU filter. Only regions. Could you please change that? 
- There seems to be a difference between the records the old record finds and the new one:
screenshots_1683563618_1833_08052023_2325x769

Any thoughts on why?

Thank you!

**Comment by ifoche** [comment]
@deeonwuli Could you please also merge it with development?

Thank you!

**Comment by deeonwuli** [comment]
> Thanks @deeonwuli .
> 
> * The report lacks from a minor thing. You cannot select countries in the OU filter. Only regions. Could you please change that?
> 
> Thank you!

@ifoche i have added this change to the main audit filters report https://github.com/EyeSeeTea/d2-reports/pull/76

**Review by ifoche — APPROVED** [review]
thanks @deeonwuli

**Pull request merged**
