### PR TITLE
Feature/data elements view

### PR DESCRIPTION
**Pull request by deeonwuli**
### :pushpin: References

 **Issue:** Closes 
- https://app.clickup.com/t/35y9v5j
- https://app.clickup.com/t/35y9vae

### CODE REVIEW

**Comment by MiquelAdell** [comment]
Hi @deeonwuli 

This switch in src/webapp/utils/reportType.ts will not work. Please take a look at the switch documentation and fix it. You should also re-test this feature once you've fixed this switch

Screenshot 2023-07-24 at 08 12 17

**Comment by MiquelAdell** [comment]
@deeonwuli I tried to compile the project as an app and I got an error.

```
→ yarn build-mal-subscription-metadata
yarn run v1.22.18
$ npx ts-node -P tsconfig-cli.json src/scripts/build-mal-subscription-metadata.ts
TypeError: Cannot read properties of undefined (reading 'split')
    at /Users/miqueladell/code/d2-reports/src/scripts/build-mal-subscription-metadata.ts:131:45
    at Generator.next (<anonymous>)
    at /Users/miqueladell/code/d2-reports/src/scripts/build-mal-subscription-metadata.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/miqueladell/code/d2-reports/src/scripts/build-mal-subscription-metadata.ts:4:12)
    at buildMetadata (/Users/miqueladell/code/d2-reports/src/scripts/build-mal-subscription-metadata.ts:103:12)
    at /Users/miqueladell/code/d2-reports/src/scripts/build-mal-subscription-metadata.ts:241:15
    at Generator.next (<anonymous>)
    at /Users/miqueladell/code/d2-reports/src/scripts/build-mal-subscription-metadata.ts:8:71
    at new Promise (<anonymous>)
npm notice 
npm notice New major version of npm available! 8.1.2 -> 9.8.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.8.1
npm notice Run npm install -g npm@9.8.1 to update!
npm notice 
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I also tested using `yarn start`.

I'm having some issues but first there is something that would make testing quite easier.
In the d2-report project you should indicate, in the PR, under "notes to the tester", what image to test against (for example dev.eyeseetea.com/who-dev-238) and which REACT_APP_REPORT_VARIANT to set up under env.local.

I guess in this particular case this is:
```
REACT_APP_DHIS2_BASE_URL=https://dev.eyeseetea.com/who-dev-238/
REACT_APP_REPORT_VARIANT=mal-subscription-status
```

I've tried both against `extranet.who.int/dhis2` and `dev.eyeseetea.com/who-dev-238` and with both I got this error:
`Unhandled Rejection (Error): Missing SQL view: MAL - Approval Dataelements`

It seems that there should be a view that is not available. Maybe there has been an error on the server and the view is not available anymore. Can you test it on your side and let me know I you see the same error?

Do you have the code of the view that seems to be missing?

**Comment by xurxodev** [comment]
@deeonwuli @MiquelAdell I've reviewed the script build-mal-subscription-metadata.ts and now seems to have its own logic and not be a copy of build-mal-metadata.ts.

**Review by MiquelAdell — APPROVED** [review]
Thanks @deeonwuli and @xurxodev

**Pull request merged**
