### PR TITLE
Feature/Per-DataElement approve action in Check Differences

### PR DESCRIPTION
**Pull request by nshandra**
### :pushpin: References

-   **Issue:** [Per-DataElement approve action in Check Differences](https://app.clickup.com/t/2z4xn6a)

### :memo: Implementation

Check Differences is no longer a bulk action.
~~Modification count seems to break now.~~ Acceptable behavior.

- The leftover selection bug is fixed buy a dialog re-render as we discussed in a meeting.
- The main form now has two "Check Difference" actions with the same user text (transparent to the user) to differentiate between submitted and un-submitted rows. This means that no API calls are necessary to check if the row is submitted.
- The main form only gets updated (approve date, revoke...) after the dialog is closed in order to decrease the workload.

Added minor fixes identified during development (present in PR#58 too):
Rename the unapprove action name to revoke for consistency sake.
fix typos and camelCase errors.
fix last date of action writing inconsistently.

### CODE REVIEW

**Review by ifoche — CHANGES_REQUESTED** [review]
Just a minor thing @nshandra . When you approve e.g. 2 values in 3, looks like the list that results thinks that you are still selecting the DEs in other pages. I guess that they should just disappear from the listing, together with the message for the selection. Is it that the selection needs to be reset after the approval action or so? Check the screenshot right after the approval action
screenshots_1663602717_1751_19092022_975x497

**Comment by nshandra** [comment]
The "zombie" selection is addressed now.

**Comment by nshandra** [comment]
> Just a minor thing @nshandra . When you approve e.g. 2 values in 3, looks like the list that results thinks that you are still selecting the DEs in other pages. I guess that they should just disappear from the listing, together with the message for the selection. Is it that the selection needs to be reset after the approval action or so? Check the screenshot right after the approval action screenshots_1663602717_1751_19092022_975x497

The "zombie" selection is addressed now.

**Review by ifoche — APPROVED** [review]
thanks @nshandra

**Pull request merged**
